name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --verbosity normal
